// const double=(num)=> num +100;
// console.log(process.argv);

[
    { id: "001",name: "Don Quixote App",rating: "8",poster: "https://d1pwnu15mzvjms.cloudfront.net/210x320/9781504044486.jpg",summary: "Often referred to as the first modern European novel, Don Quixote follows the exploits of the titular noble who becomes obsessed with the romantic notion of chivalry.",trailer: "https://www.youtube.com/embed/yiiRZJUTT2k"},
    { id: "003",name: "Harry Potter",rating: "8.5",poster: "https://orion-uploads.openroadmedia.com/sm_9333ba5b72d2-hp.jpg",summary: "The most recent novel on this list, Harry Potter and the Sorcerer’s Stone brings readers into a world of magic at Hogwarts School of Witchcraft and Wizardry.",trailer: "https://www.youtube.com/embed/VyHV0BRtdxo"},
    { id: "004",name: " There Were None",rating: "7",poster: "https://orion-uploads.openroadmedia.com/sm_e82064-and-then-there-were-none.jpg",summary: "From acclaimed mystery author Agatha Christie, And Then There Were None is a mastery of tension. ",trailer: "https://www.youtube.com/embed/zNzgvYdjRRI"},
    { id: "005",name: "Atitude Everythink",rating: "6",poster: "https://i.pinimg.com/originals/48/16/db/4816db6e3a276f5795683058a13015b2.jpg",summary: " The author explains using multiple examples instead of giving some soul-deep theories, which makes it easy to comprehend.",trailer: "https://www.youtube.com/embed/ojQangi3poc"}
]
db.books.insertMany([
    { id: "001",name: "Don Quixote App",rating: "8",poster: "https://d1pwnu15mzvjms.cloudfront.net/210x320/9781504044486.jpg",summary: "Often referred to as the first modern European novel, Don Quixote follows the exploits of the titular noble who becomes obsessed with the romantic notion of chivalry.",trailer: "https://www.youtube.com/embed/yiiRZJUTT2k"},
    { id: "003",name: "Harry Potter",rating: "8.5",poster: "https://orion-uploads.openroadmedia.com/sm_9333ba5b72d2-hp.jpg",summary: "The most recent novel on this list, Harry Potter and the Sorcerer’s Stone brings readers into a world of magic at Hogwarts School of Witchcraft and Wizardry.",trailer: "https://www.youtube.com/embed/VyHV0BRtdxo"},
    { id: "004",name: " There Were None",rating: "7",poster: "https://orion-uploads.openroadmedia.com/sm_e82064-and-then-there-were-none.jpg",summary: "From acclaimed mystery author Agatha Christie, And Then There Were None is a mastery of tension. ",trailer: "https://www.youtube.com/embed/zNzgvYdjRRI"},
    { id: "005",name: "Atitude Everythink",rating: "6",poster: "https://i.pinimg.com/originals/48/16/db/4816db6e3a276f5795683058a13015b2.jpg",summary: " The author explains using multiple examples instead of giving some soul-deep theories, which makes it easy to comprehend.",trailer: "https://www.youtube.com/embed/ojQangi3poc"},
    { id: "006",name: "Elan  musk",rating: "9",poster: "https://static.displate.com/280x392/displate/2021-05-06/eeccb2c743a3c5f26e6d7b0b1bf2cb6a_72e8b3c84e940c49c49ded93f03e372e.jpg",summary: "He is the founder, CEO and chief engineer of SpaceX; angel investor, CEO and product architect of Tesla, Inc.; owner and CEO of Twitter, Inc.; founder of the Boring Company; co-founder of Neuralink and OpenAI; and president of the philanthropic Musk Foundation.",trailer: "https://www.youtube.com/embed/ojQangi3poc"},
    { id: "007",name: "Elan  musk point 2",rating: "10",poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg/1200px-Elon_Musk_Royal_Society_%28crop2%29.jpg",summary: "He is the founder, CEO and chief engineer of SpaceX; angel investor, CEO and product architect of Tesla, Inc.; owner and CEO of Twitter, Inc.; founder of the Boring Company; co-founder of Neuralink and OpenAI; and president of the philanthropic Musk Foundation.",trailer: "https://www.youtube.com/embed/ojQangi3poc"}

]);
db.books.insertMany([
    { id: "006",name: "Elan  musk",rating: "9",poster: "https://static.displate.com/280x392/displate/2021-05-06/eeccb2c743a3c5f26e6d7b0b1bf2cb6a_72e8b3c84e940c49c49ded93f03e372e.jpg",summary: "He is the founder, CEO and chief engineer of SpaceX; angel investor, CEO and product architect of Tesla, Inc.; owner and CEO of Twitter, Inc.; founder of the Boring Company; co-founder of Neuralink and OpenAI; and president of the philanthropic Musk Foundation.",trailer: "https://www.youtube.com/embed/ojQangi3poc"},
    { id: "007",name: "Elan  musk point 2",rating: "10",poster: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Elon_Musk_Royal_Society_%28crop2%29.jpg/1200px-Elon_Musk_Royal_Society_%28crop2%29.jpg",summary: "He is the founder, CEO and chief engineer of SpaceX; angel investor, CEO and product architect of Tesla, Inc.; owner and CEO of Twitter, Inc.; founder of the Boring Company; co-founder of Neuralink and OpenAI; and president of the philanthropic Musk Foundation.",trailer: "https://www.youtube.com/embed/ojQangi3poc"}
]);